// Real press & media features, harvested from the original yurybettoni.com Press archive.
// Each links to the original source (YouTube/Vimeo interviews, magazine features, PDFs).
// Kept as data so the Press hub and Athlete highlights stay in sync.

export type PressItem = {
  title: string;
  date: string;            // ISO yyyy-mm-dd
  category: "Tennis" | "Construction";
  kind: "video" | "article";
  summary: string;
  youtube?: string;        // 11-char id, when the source is a YouTube video
  vimeo?: string;          // numeric id, when the source is a Vimeo video
  href: string;            // canonical external source
};

export const PRESS: PressItem[] = [
  {
    title: "From the Court to Recovery: Bettoni on Peain Script™ Cream",
    date: "2025-07-25",
    category: "Tennis",
    kind: "video",
    summary: "Yury Bettoni is featured in a commercial for Peain Script, where professional tennis player talks about the efficiency of Peain Script™ pain relief cream.",
    youtube: "f9Ada9fMAUw",
    href: "https://www.youtube.com/watch?v=f9Ada9fMAUw",
  },
  {
    title: "Sport, Style, and a Life of Purpose",
    date: "2025-07-25",
    category: "Tennis",
    kind: "video",
    summary: "In this interview, Yury Bettoni shares insights into his journey from professional tennis to luxury design, highlighting his training at the Nick Bollettieri Tennis Academy and his role as a partner at Italkraft. He discusses the fusion of sports discipline with creative projects, showcasing his multifaceted career. Bettoni also reflects on his upbringing in Africa.",
    youtube: "4NVWDYNoal8",
    href: "https://www.youtube.com/watch?v=4NVWDYNoal8",
  },
  {
    title: "Bettoni’s Training Spotlight at the Miami Open",
    date: "2025-07-25",
    category: "Tennis",
    kind: "video",
    summary: "In this 2013 Miami Open promotional video, Yury Bettoni showcases his dynamic training techniques, highlighting the integration of explosive movement and functional strength. Filmed at the Tennis Center at Crandon Park, the video captures Bettoni’s commitment to enhancing athletic performance, reflecting the high-energy atmosphere of the tournament.",
    youtube: "5Ix-M5Mu-9o",
    href: "https://www.youtube.com/watch?v=5Ix-M5Mu-9o",
  },
  {
    title: "Bettoni Unveils the MSPI Advantage",
    date: "2025-07-25",
    category: "Tennis",
    kind: "video",
    summary: "Yury Bettoni presents the cutting-edge MSPI training facility, demonstrating advanced methods and equipment designed to elevate athletic performance. This commercial highlights his expertise in blending technology with innovative training techniques to maximize results.",
    youtube: "olRsICu8cTM",
    href: "https://www.youtube.com/watch?v=olRsICu8cTM",
  },
  {
    title: "Bettoni’s Roots in Elite Performance",
    date: "2025-07-25",
    category: "Tennis",
    kind: "video",
    summary: "Yury Bettoni is a former professional tennis player who trained at the renowned Nick Bollettieri Tennis Academy (now IMG Academy) in Florida. His athletic background and experience at IMG have influenced his approach to sports performance and training methodologies. Additionally, Bettoni has been recognized by the Gatorade Sports Science Institute at IMG Academy for his.",
    youtube: "ZyuwVmM7r9o",
    href: "https://www.youtube.com/watch?v=ZyuwVmM7r9o",
  },
  {
    title: "Bettoni Introduces the Y-System",
    date: "2025-07-25",
    category: "Tennis",
    kind: "video",
    summary: "Yury Bettoni shares his journey from professional tennis to developing the innovative Y-System training methodology focused on explosive movement and functional strength. He reflects on his experiences at the Nick Bollettieri Tennis Academy and collaborations with top tennis players, offering valuable insights into advancing athletic performance.",
    youtube: "bf21tR1es6I",
    href: "https://www.youtube.com/watch?v=bf21tR1es6I",
  },
  {
    title: "Bettoni Unpacks His Y-System Method",
    date: "2025-07-25",
    category: "Tennis",
    kind: "video",
    summary: "In this interview from the 100th Anniversary of Miami Beach Exhibition, Yury Bettoni discusses his evolution from ATP tennis pro to innovator in sports training. He shares insights into his Y-System methodology, emphasizing explosive movement and functional strength to enhance athletic performance. Bettoni also reflects on his experiences at the Nick Bollettieri Tennis Academy and.",
    youtube: "_Tl9eFuUVug",
    href: "https://www.youtube.com/watch?v=_Tl9eFuUVug",
  },
  {
    title: "Bettoni Demonstrates the Power of IMOOVE",
    date: "2025-07-25",
    category: "Tennis",
    kind: "video",
    summary: "In this commercial, Yury Bettoni demonstrates the IMOOVE, a cutting-edge training device designed to enhance athletic performance. The video showcases Bettoni’s expertise in integrating innovative equipment into training routines, highlighting his commitment to advancing sports training methodologies. Viewers can gain insight into how such tools can be utilized to improve strength, agility, and overall athleticism.",
    youtube: "BAp4Ly4MCsg",
    vimeo: "131249038",
    href: "https://www.youtube.com/watch?v=BAp4Ly4MCsg",
  },
  {
    title: "Yury Bettoni & Carol Alt in Timeless Harmony",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "Yury Bettoni and Carol Alt are elegantly captured in an intimate photo series that showcases their genuine connection and refined style. This feature offers a glimpse into their shared moments of grace and partnership.",
    href: "https://www.kikapress.com/gallery/carol-alt-e-yury-bettoni-romantici-a-roma",
  },
  {
    title: "Bettoni Showcases Italkraft’s Work at Murano",
    date: "2025-07-25",
    category: "Construction",
    kind: "article",
    summary: "This article showcases Italkraft’s remarkable craftsmanship at Murano at Portofino, one of Miami’s most prestigious residential developments. The feature highlights the elegant, custom-designed kitchen that seamlessly blends functionality with sophisticated aesthetics. Yury Bettoni, who was closely involved in the project, offers his personal insight and appreciation for the beauty and quality of the kitchen Italkraft.",
    href: "https://heyzine.com/flip-book/793eea1582.html",
  },
  {
    title: "Bettoni Explores Miami’s Luxury Growth",
    date: "2025-07-25",
    category: "Construction",
    kind: "article",
    summary: "Yury Bettoni offers expert insight on Miami’s evolving real estate scene, highlighting the growth of neighborhoods like South of Fifth. His perspective combines local knowledge with a passion for luxury design.",
    href: "https://www.elliman.com/insider/miami-up-and-comers",
  },
  {
    title: "Yury Bettoni’s Journey into Luxury Design",
    date: "2025-07-25",
    category: "Construction",
    kind: "article",
    summary: "In the inaugural issue of ELEVATE by Italkraft, Yury Bettoni shares insights into his journey from professional tennis to luxury design, highlighting his collaboration with Italkraft on projects like Zaha Hadid’s One Thousand Museum. The magazine delves into Bettoni’s passion for craftsmanship and his commitment to excellence in both sports and design.",
    href: "https://issuu.com/italkraft/docs/elevate_italkraft_magazine___fall_i",
  },
  {
    title: "Bettoni Joins MODAMIAMI Icons",
    date: "2025-07-25",
    category: "Construction",
    kind: "article",
    summary: "At MODAMIAMI 2025, Yury Bettoni joined luminaries like Bret David and Magnus Walker at the Biltmore Hotel in Coral Gables, celebrating rare automobiles, luxury design, and community. The event showcased Bettoni’s seamless integration of elegance and performance, reflecting his multifaceted career and passion for excellence.",
    href: "https://worldredeye.com/2025/03/modamiami-at-the-biltmore/",
  },
  {
    title: "A Celebration of Art and Innovation in Wynwood",
    date: "2025-07-25",
    category: "Construction",
    kind: "article",
    summary: "At the exclusive grand opening of Italkraft Wynwood during Art Basel 2019, Yury Bettoni joined artist Alê Jordão and other notable guests to celebrate the fusion of contemporary art and luxury design. The event highlighted Bettoni’s commitment to elevating Miami’s design scene through partnerships that blend aesthetics with functionality.",
    href: "https://worldredeye.com/2019/12/italkraft-wynwood-opening-ale-jordao-during-art-basel-2019-at-italkraft-wynwood-showroom/",
  },
  {
    title: "Bettoni Tours South Beach in the Lexus LS",
    date: "2025-07-25",
    category: "Construction",
    kind: "article",
    summary: "In the February 2018 issue of Modern Luxury, Yury Bettoni takes the wheel of a 2018 Lexus LS to explore South Beach’s architectural icons, including his latest project at One Thousand Museum. This feature highlights Bettoni’s seamless blend of design passion and professional excellence.",
    href: "https://digital.modernluxury.com/hbmi-feb-2018?i=471698",
  },
  {
    title: "Bettoni’s Leap into Luxury Design",
    date: "2025-07-25",
    category: "Construction",
    kind: "article",
    summary: "In a feature by the Miami Herald, Yury Bettoni discusses his journey from professional tennis to entrepreneurship, highlighting his role as a partner at Italkraft and his commitment to excellence in design. The article delves into his experiences and the passion that drives his ventures.",
    href: "https://www.miamiherald.com/indulge/article240895051.html",
  },
  {
    title: "Yury Bettoni’s Life in Miami",
    date: "2025-07-25",
    category: "Construction",
    kind: "article",
    summary: "Yury Bettoni shares his favorite spots and lifestyle in Miami’s SoFi neighborhood, from local eateries to the park where he developed his Y System training. His story reflects a deep connection to the community and a balance of work and relaxation.",
    href: "https://www.elliman.com/insider/neighborhood-sofi-miami",
  },
  {
    title: "Inside Yury Bettoni’s World",
    date: "2025-07-25",
    category: "Construction",
    kind: "article",
    summary: "In an exclusive feature on S. Florida Business & Wealth, Yury Bettoni offers a glimpse into his refined lifestyle, blending his Ethiopian roots with a passion for Italian craftsmanship and luxury. From his cherished Sardinian landscapes to collaborations with Italkraft on high-end projects like Zaha Hadid’s One Thousand Museum, Bettoni’s vision board reflects a life.",
    href: "https://sfbwmag.com/vision-board/",
  },
  {
    title: "Bettoni’s Journey to Italkraft",
    date: "2025-07-25",
    category: "Construction",
    kind: "article",
    summary: "In an exclusive feature on +Beryll’s Journal, Yury Bettoni shares his extraordinary journey from Ethiopia to the U.S., detailing his evolution from a professional tennis player to a partner at Italkraft. Discover how a serendipitous encounter led to collaborations on iconic projects like Zaha Hadid’s One Thousand Museum, blending Bettoni’s passion for design with his.",
    href: "https://beryll.com/blogs/journal/italkraft?srsltid=AfmBOorTuVE0vNxmue9sPBQ98TbtKepNdiH33p7tSpGjIdRlBBgqxKtg",
  },
  {
    title: "Bettoni’s Rise as a U.S. Tennis Influencer",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "Yury Bettoni stands out as a top tennis influencer in the U.S., blending pro-level expertise with entrepreneurial ventures and social impact initiatives. Follow his journey as he inspires thousands with insights on tennis, fitness, and giving back through his foundation.",
    href: "https://www.influencer-hero.com/top-influencers/top-70-tennis-influencers-in-the-us",
  },
  {
    title: "Bettoni and Shubert at the Miami Open",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "Yury Bettoni is featured in the “Photos” section of Tom Shubert’s website, where he is seen practicing with Shubert at the Miami Open. This collaboration highlights Bettoni’s ongoing involvement in the tennis community and his commitment to the sport.",
    href: "https://www.tshubert.com/photos",
  },
  {
    title: "Bettoni and Groeneveld’s Shared Tennis Path",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "Yury Bettoni is featured in the TennisDirect Blog through memorable moments shared with coach Sven Groeneveld, highlighting their friendship and mutual passion for tennis. Their stories offer a unique, behind-the-scenes look at life on the professional tour.",
    href: "https://tennisdirectblog.wordpress.com/",
  },
  {
    title: "Yury Bettoni Talks Training and Aesthetics",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "In a 2015 feature on TGCOM24’s Speciale TV Moda, former ATP pro and IMG Academy coach Yury Bettoni shares insights on fitness, training techniques, and athletic style. The article showcases Bettoni’s approach to blending performance with aesthetics, offering a glimpse into the mindset of a top-tier tennis professional.",
    href: "https://www.tgcom24.mediaset.it/speciale-tv-moda/foto/yury-bettoni_2101504-2015.shtml",
  },
  {
    title: "Speed Meets Precision: Bettoni Trains with VertiMax Raptor",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "In a recent VertiMax blog post, Yury Bettoni demonstrates how the VertiMax Raptor enhances tennis performance. The article highlights Bettoni’s agility drills, showcasing the system’s ability to improve lateral movement and explosive speed. With endorsements from professionals like Maria Sharapova and the USTA, VertiMax is recognized as a premier training tool for aspiring champions.",
    href: "https://vertimax.com/blog/best-tennis-training-equipment-win-wimbledon",
  },
  {
    title: "Behind the Scenes with Champions: Bettoni’s Favorite Coaching Memories",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "In his article “Coach Confessions: 5 Favorite Moments With Champions,” Yury Bettoni shares memorable experiences from his coaching career, including interactions with tennis legends like Mary Pierce and Roger Federer. He reflects on the camaraderie and challenges of life on the tour, offering readers an insider’s perspective on the world of professional tennis.",
    href: "https://tennisnow.com/news/2019/june/coach-confessions-5-favorite-moments-with-champio.aspx",
  },
  {
    title: "From the Tour to the Trenches: Yury Bettoni Opens Up",
    date: "2025-07-25",
    category: "Tennis",
    kind: "video",
    summary: "Watch former ATP pro Yury Bettoni share insights from his playing days and coaching career in this candid interview. From training with legends to overcoming challenges on tour, Bettoni’s story offers rare, inspiring perspectives for tennis fans and aspiring players alike.  Yury Bettoni | Former ATP Tennis Pro – Sweat It Out | iHeart.",
    youtube: "PyC-PfPvOec",
    href: "https://www.youtube.com/watch?v=PyC-PfPvOec",
  },
  {
    title: "More Than a Coach: Yury Bettoni Remembers Peter Lundgren",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "In a heartfelt tribute, Yury Bettoni reveals the personal side of legendary coach Peter Lundgren—his generosity, humility, and unforgettable moments behind the scenes. Discover the story of a simple airport wait that speaks volumes about their deep bond and Lundgren’s lasting impact on the tennis world.",
    href: "https://www.tennis-prose.com/bios/lundgren-remembered-by-bettoni/",
  },
  {
    title: "From Court to Column: Yury Bettoni Joins Last Word on Tennis",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "Former pro‑turned‑journalist Yury Bettoni brings a distinct insider’s voice to Last Word on Tennis, blending high‑performance expertise with entrepreneurial savvy. Expect informed commentary drawn from his years training under Bollettieri, hitting with champions like Federer, and building his own coaching system and foundation—offering depth and nuance few others can match.",
    href: "https://lastwordonsports.com/tennis/author/yurybettoni/",
  },
  {
    title: "The Godfather’s Legacy: Bettoni Reflects on Bollettieri’s Brilliance",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "Former Nick Bollettieri Academy player and respected coach Yury Bettoni shares why Nick Bollettieri: Godfather of Modern Tennis captures the energy, discipline, and vision that shaped champions. His reflections highlight how Bollettieri’s legacy continues to inspire those pursuing excellence on and off the court.",
    href: "https://www.tennis-prose.com/articles/my-nick-bollettieri-book-earning-rave-reviews/",
  },
  {
    title: "How should Rodger Federer retire?",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "Yury Bettoni (Former pro player and Federer hitting partner): “While pretty much everyone expects Roger to retire in the temple of tennis, Wimbledon center court, I would say during Davis Cup, a homage to Peter Carter. As you know, having shared in first person unique moments with both I would definitely say that for Roger.",
    href: "https://www.tennis-prose.com/bios/how-should-roger-federer-retire/",
  },
  {
    title: "Power Meets Precision: Dunlop Teams Up with Yury Bettoni",
    date: "2025-07-25",
    category: "Tennis",
    kind: "article",
    summary: "Dunlop Sports has announced its official sponsorship of internationally acclaimed tennis coach Yury Bettoni. Known for training elite athletes and contributing to global player development, Bettoni brings his extensive expertise and innovation to Dunlop’s performance-driven mission. The partnership represents a shared vision for excellence at the highest level of the sport.",
    href: "https://www.dropbox.com/scl/fi/6pff9nat9ie3ctqam2vil/Dunlop-Sports-Announces-Sponsorship-of-Yury-Bettoni-FINAL.pdf?rlkey=cduthqyvsijxecfj4daskegax&st=o9izpyqa&dl=0",
  },
  {
    title: "Yury Bettoni Reviews Dunlop’s Game-Changing Gear",
    date: "2025-07-24",
    category: "Tennis",
    kind: "article",
    summary: "Renowned coach and former Federer hitting partner Yury Bettoni shares his expert perspective on Dunlop’s latest gear, detailing how its superior grip and comfort elevate player performance. His insights offer a rare look at how top-quality equipment supports the demands of high-level training and match play.",
    href: "https://www.tennis-prose.com/articles/scoop/dunlop-product-review/",
  },
  {
    title: "From Ethiopia to Federer: Yury Bettoni’s Rise",
    date: "2025-07-24",
    category: "Tennis",
    kind: "article",
    summary: "From a late introduction to tennis in Ethiopia to training alongside legends like Roger Federer, Yury Bettoni’s journey weaves together elite sport, resilience, and entrepreneurial success. Discover how his unique path from the professional tour to building impactful ventures continues to inspire those pursuing excellence on and off the court. Biofile: Yury Bettoni Interview.",
    href: "https://www.tennis-prose.com/articles/scoop/biofile-yury-bettoni-interview/",
  },
];
